### PR TITLE
update version.h

### PR DESCRIPTION
**Pull request by Fishrock123**
Not sure if this needed, if not, I'll just remove it. :)

### CODE REVIEW

**Comment by indutny** [comment]
Makes sense!

**Comment by indutny** [comment]
Thanks

**Comment by Fishrock123** [comment]
@indutny is this file actually... used?

**Comment by indutny** [comment]
Yep, `core2dump -v` will print data from it.

**Comment by Fishrock123** [comment]
Doh. Missed that. Not used to C-style includes.

**Pull request merged**
